<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-64CO17K" failures="2" tests="17" name="testCases.TC_003_LoginDDT2_trycatch" time="161.241" errors="0" timestamp="2023-07-21T18:43:35 IST" skipped="0">
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.094"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.010"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="11.696"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="7.488"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.044"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="1.101">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.TC_003_LoginDDT2_trycatch.test_DDT(TC_003_LoginDDT2_trycatch.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_DDT -->
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.215"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.000"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.091"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="11.982"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="7.782"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="4.931"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.066"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.077"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="1.160">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testCases.TC_003_LoginDDT2_trycatch.test_DDT(TC_003_LoginDDT2_trycatch.java:67)
at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_DDT -->
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="12.213"/>
  <testcase classname="testCases.TC_003_LoginDDT2_trycatch" name="test_DDT" time="6.291"/>
</testsuite> <!-- testCases.TC_003_LoginDDT2_trycatch -->
